# A string used to distinguish different Supabase projects on the same host. Defaults to the working directory name when running `supabase init`.
project_id = "qumgxoscwrygwykbojym"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[api.tls]
enabled = false

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"

[db.seed]
enabled = true
sql_paths = ["./seed.sql"]

[realtime]
enabled = true
bind_address = "0.0.0.0"
ip_version = "IPv4"
max_header_length = 4096

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
smtp_port = 54325
web_port = 54324

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = [
  "http://localhost:3000/auth/callback",
  "http://localhost:3000/dashboard",
  "http://localhost:3000/auth/verify",
  "http://localhost:3000/auth/reset-password"
]
jwt_expiry = 3600
enable_signup = true
enable_anonymous_sign_ins = false
enable_double_opt_in = false

[auth.email]
enable_signup = true
double_opt_in = false
enable_confirmations = true

[auth.email.template]
confirm = ""
recovery = ""
invite = ""

[auth.sms]
enable_signup = true
max_frequency = "10s"

[analytics]
enabled = false
port = 54327
vector_port = 54328

[functions]
verify_jwt = false
