#!/bin/bash

# TalentSphere Database Migration Script
# This script applies all migrations to your Supabase instance

SUPABASE_URL="https://qumgxoscwrygwykbojym.supabase.co"
SUPABASE_ANON_KEY="sb_publishable_l-dfy9OyxcxjIk0B6ZKVfw_x5COEbPi"

echo "=============================================="
echo "TalentSphere Database Migration Tool"
echo "=============================================="
echo ""
echo "Project: qumgxoscwrygwykbojym"
echo "URL: $SUPABASE_URL"
echo ""
echo "IMPORTANT: This script requires you to run the SQL manually in Supabase Dashboard"
echo ""
echo "Steps to apply migrations:"
echo "1. Go to: https://qumgxoscwrygwykbojym.supabase.co/project/qumgxoscwrygwykbojym/editor"
echo "2. Navigate to SQL Editor (left sidebar)"
echo "3. Click 'New Query'"
echo "4. Copy and paste the contents of: supabase/ALL_MIGRATIONS_COMBINED.sql"
echo "5. Click 'Run' to execute all migrations"
echo ""
echo "Alternatively, apply each migration file individually in order:"
echo "  - 001_core_extensions_enums.sql"
echo "  - 002_users_organizations.sql"
echo "  - 003_jobs_applications.sql"
echo "  - 004_lms.sql"
echo "  - 005_challenges.sql"
echo "  - 006_gamification_notifications.sql"
echo "  - 007_rls_policies.sql"
echo "  - 008_auth_trigger_functions.sql"
echo ""
echo "After applying migrations:"
echo "1. Go to Storage in Supabase Dashboard"
echo "2. Create these buckets:"
echo "   - avatars (public)"
echo "   - resumes (private)"
echo "   - course-content (private)"
echo "   - portfolio (public)"
echo ""
echo "3. Go to Authentication → Providers"
echo "4. Enable Email provider"
echo "5. Add redirect URLs:"
echo "   - http://localhost:3000"
echo "   - http://localhost:3000/auth/callback"
echo "   - http://localhost:3000/dashboard"
echo ""
echo "=============================================="
